version: 2
updates:
- package-ecosystem: pip
  directory: "/etc"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: django-sass-processor
    versions:
    - 0.8.2
    - 1.0.0
  - dependency-name: markdownify
    versions:
    - 0.6.3
    - 0.6.4
    - 0.6.5
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: cffi
    versions:
    - 1.14.4
  - dependency-name: django-q
    versions:
    - 1.3.4
  - dependency-name: django
    versions:
    - 2.2.13
  - dependency-name: bleach
    versions:
    - 3.1.4
  - dependency-name: django-compressor
    versions:
    - "2.4"
  - dependency-name: gunicorn
    versions:
    - 20.0.4
