# Generated by Django 2.1.7 on 2019-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='routings',
        ),
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
