# Generated by Django 2.1.7 on 2019-03-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackdestination',
            name='channel_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackdestination',
            name='team_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
