# Generated by Django 2.1.7 on 2019-03-06 00:02

from django.db import migrations, models


def add_admessages(apps, schema_editor):
    AdMessage = apps.get_model('announcements', 'AdMessage')
    AdMessage(text='Developed on GitHub. <https://github.com/dcollinsn/judge-announcements/|Pull requests welcome!>').save()
    AdMessage(text='Manage a Slack workspace? <https://announcements.magicjudges.org/|Add this integration!>').save()


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20190305_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RunPython(add_admessages),
    ]
