# Generated by Django 2.1.7 on 2019-03-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_admessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesource',
            name='order',
            field=models.IntegerField(default=0, help_text='Key to sort by in user-facing views'),
        ),
    ]
