# Generated by Django 2.1.7 on 2019-03-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20190327_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemplarAnnouncement',
            fields=[
                ('announcement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcements.Announcement')),
                ('days_out', models.IntegerField(help_text='Nominal number of days out until the wave closes')),
                ('wave_id', models.IntegerField(help_text='JudgeApps ID of the exemplar wave in question')),
                ('wave_name', models.CharField(help_text='Exemplar wave name', max_length=64)),
                ('wave_deadline', models.DateTimeField(help_text='Deadline of exemplar wave in question')),
            ],
            options={
                'abstract': False,
            },
            bases=('announcements.announcement',),
        ),
        migrations.CreateModel(
            name='ExemplarSource',
            fields=[
                ('messagesource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='announcements.MessageSource')),
                ('current_wave_id', models.IntegerField(help_text='JudgeApps ID of the current exemplar wave')),
                ('current_wave_name', models.CharField(help_text='Name of the current exemplar wave', max_length=64)),
                ('current_wave_deadline', models.DateTimeField(help_text='Deadline of the current exemplar wave')),
                ('last_reminder', models.IntegerField(default=99, help_text='What was the last reminder that was sent? (number of days prior to deadline) Used to track what announcement to send next.')),
                ('polling_interval', models.IntegerField(default=10, help_text='Polling interval in minutes')),
                ('last_polled', models.DateTimeField(blank=True, help_text='Last successful poll', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('announcements.messagesource',),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('M', 'Manual Announcement'), ('F', 'JudgeApps Forum Post'), ('B', 'MagicJudges Blog'), ('E', 'Exemplar Deadline')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='source_type',
            field=models.CharField(choices=[('M', 'Manual Announcement'), ('F', 'JudgeApps Forum Post'), ('B', 'MagicJudges Blog'), ('E', 'Exemplar Deadline')], default='', max_length=1),
        ),
    ]
