# Generated by Django 2.2rc1 on 2019-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_manualsource_public_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesource',
            name='default_source',
            field=models.BooleanField(default=False, help_text='Default sources are automatically added to newly connected destinations.'),
        ),
    ]
