# Generated by Django 2.2rc1 on 2019-10-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_messagesource_default_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='admessage',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement_type',
            field=models.CharField(choices=[('M', 'Manual Announcement'), ('F', 'JudgeApps Forum Post'), ('B', 'WordPress Blog'), ('E', 'Exemplar Deadline')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='messagesource',
            name='source_type',
            field=models.CharField(choices=[('M', 'Manual Announcement'), ('F', 'JudgeApps Forum Post'), ('B', 'WordPress Blog'), ('E', 'Exemplar Deadline')], default='', max_length=1),
        ),
    ]
